### PR TITLE
Remove jquery dependency

### LINKED ISSUE #124: Doesn't load under jQuery 1.8.1
Sizzle is unable to parse some expression:

```
Syntax error, unrecognized expression:  :not(:has(
```

(This is on master)

### LINKED ISSUE #670: jQuery dependency
Are there plans to remove the jquery dependency?
Modern browsers don't really need it.
A separate polyfill can be used for old browsers.

Making MathQuill self contained without external dependencies will make it smaller and easier to integrate MathQuill with Angular/React project

### LINKED ISSUE #870: Security vulnerabilities: update to jQuery 3.4.0
Running `npm audit` yields the following security vulnerabilities for mathquill's jQuery dependency:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting (XSS)                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mathquill                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mathquill > jquery                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/328                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.4.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mathquill                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mathquill > jquery                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/796                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

Please update the jQuery dependency to >=3.4.0 to fix these urgent security issues.

### LINKED ISSUE #929: does not work when replace jquery to zepto on mobile pages
it seems the api are most compatible between zepto and jquery

### LINKED ISSUE #1007: Remove jQuery dependency
jQuery is bad and is bloat. is there alternative without jQuery?

### PR DESCRIPTION
**Pull request by jwmerrill**
Remove MathQuill's jQuery dependency, and replace it with a few smaller internal libs:
* A DOM builder function to replace usage of jQuery to parse html strings: https://github.com/mathquill/mathquill/blob/2573c3a3cf3a97a26fe65e3074b0fd424ca0bc41/src/dom.ts#L58-L62
* A `DOMFragment` class to represent and manipulate a contiguous span of sibling DOM nodes. This is closely analogous to MathQuill's existing `Fragment` class used to represent and manipulate a contiguous span of sibling parse nodes. It replaces uses of jQuery for inserting/removing/moving DOM nodes and class manipulation: https://github.com/mathquill/mathquill/blob/2573c3a3cf3a97a26fe65e3074b0fd424ca0bc41/src/domFragment.ts#L2-L4

Replace's Mathquill's bespoke HTML string templating system `DOMView` to render an element to a DOM node given its child blocks: https://github.com/mathquill/mathquill/blob/2573c3a3cf3a97a26fe65e3074b0fd424ca0bc41/src/commands/math.ts#L80-L85

Example usage: https://github.com/mathquill/mathquill/pull/1031/files#diff-7c2d826f0b8e66e11528a7f992b1e755f0e505ac76dff64bb1f3f7ee1458c4b7L15-R22

Note: introduces a new interface version (v3) because there were a couple places that the public API was returning jQuery types (or passing them as parameters to callbacks). See changelog for details.

`demosinc/mathquill` PRs:
* https://github.com/desmosinc/mathquill/pull/184
* https://github.com/desmosinc/mathquill/pull/186
* https://github.com/desmosinc/mathquill/pull/187
* https://github.com/desmosinc/mathquill/pull/188
* https://github.com/desmosinc/mathquill/pull/189
* https://github.com/desmosinc/mathquill/pull/190
* https://github.com/desmosinc/mathquill/pull/191
* https://github.com/desmosinc/mathquill/pull/193
* https://github.com/desmosinc/mathquill/pull/194
* https://github.com/desmosinc/mathquill/pull/195
* https://github.com/desmosinc/mathquill/pull/196
* https://github.com/desmosinc/mathquill/pull/198
* https://github.com/desmosinc/mathquill/pull/199
* https://github.com/desmosinc/mathquill/pull/201
* https://github.com/desmosinc/mathquill/pull/202
* https://github.com/desmosinc/mathquill/pull/203
* https://github.com/desmosinc/mathquill/pull/204
* https://github.com/desmosinc/mathquill/pull/205
* https://github.com/desmosinc/mathquill/pull/206
* https://github.com/desmosinc/mathquill/pull/207
* https://github.com/desmosinc/mathquill/pull/208
* https://github.com/desmosinc/mathquill/pull/209
* https://github.com/desmosinc/mathquill/pull/211
* https://github.com/desmosinc/mathquill/pull/212
* https://github.com/desmosinc/mathquill/pull/213
* https://github.com/desmosinc/mathquill/pull/214
* https://github.com/desmosinc/mathquill/pull/215
* https://github.com/desmosinc/mathquill/pull/216
* https://github.com/desmosinc/mathquill/pull/217
* https://github.com/desmosinc/mathquill/pull/219
* https://github.com/desmosinc/mathquill/pull/220
* https://github.com/desmosinc/mathquill/pull/221
* https://github.com/desmosinc/mathquill/pull/222
* https://github.com/desmosinc/mathquill/pull/223
* https://github.com/desmosinc/mathquill/pull/224
* https://github.com/desmosinc/mathquill/pull/225
* https://github.com/desmosinc/mathquill/pull/226
* https://github.com/desmosinc/mathquill/pull/227
* https://github.com/desmosinc/mathquill/pull/229
* https://github.com/desmosinc/mathquill/pull/230
* https://github.com/desmosinc/mathquill/pull/231
* https://github.com/desmosinc/mathquill/pull/233
* https://github.com/desmosinc/mathquill/pull/234
* https://github.com/desmosinc/mathquill/pull/235
* https://github.com/desmosinc/mathquill/pull/237
* https://github.com/desmosinc/mathquill/pull/238
* https://github.com/desmosinc/mathquill/pull/239
* https://github.com/desmosinc/mathquill/pull/240
* https://github.com/desmosinc/mathquill/pull/241
* https://github.com/desmosinc/mathquill/pull/243

Fixes https://github.com/mathquill/mathquill/issues/1007
Fixes https://github.com/mathquill/mathquill/issues/929
Fixes https://github.com/mathquill/mathquill/issues/870
Fixes https://github.com/mathquill/mathquill/issues/670
Fixes https://github.com/mathquill/mathquill/issues/124

### CODE REVIEW

File: src/tree.ts [hunk 1]
```diff
@@ -122,59 +74,41 @@ function foldNodes<T>(
...
-type HTMLElementTrackingNode = {
+type ElementTrackingNode = {
   mqBlockNode?: NodeBase;
   mqCmdNode?: NodeBase;
 };
 
-type Ends = {
-  [L]: NodeRef;
-  [R]: NodeRef;
+type Ends<T> = {
```
Comment (kschaefe) [inline src/tree.ts:82]: Should this be `T extends NodeRef`?

File: src/cursor.ts [hunk 2]
```diff
@@ -41,30 +45,42 @@ class Cursor extends Point {
     options: CursorOptions,
     controller: Controller
```
Comment (kschaefe) [inline src/cursor.ts:46]: Make `private` and remove the members and assignment in the constructor.

File: src/controller.ts [hunk 3]
```diff
@@ -1,24 +1,45 @@
...
   KIND_OF_MQ: KIND_OF_MQ;
-  textarea: $ | undefined;
-  textareaSpan: $ | undefined;
-  mathspeakSpan: $ | undefined;
 
-  constructor(root: ControllerRoot, container: $, options: CursorOptions) {
+  textarea: HTMLElement | undefined;
+  private textareaEventListeners: Partial<{
+    [K in keyof HTMLElementEventMap]: (event: HTMLElementEventMap[K]) => any;
+  }> = {};
```
Comment (kschaefe) [inline src/controller.ts:33]: Use `Record` instead of creating your own indexed type.

File: src/controller.ts [hunk 4]
```diff
@@ -1,24 +1,45 @@
...
+  HandlerOptions[HandlersWithoutDirection]
+>;
+
 class ControllerBase {
   id: number;
   data: ControllerData;
-  root: ControllerRoot;
-  container: $;
+  readonly root: ControllerRoot;
+  readonly container: HTMLElement;
```
Comment (kschaefe) [inline src/controller.ts:20]: Remove in favor of constructor definition.

File: src/controller.ts [hunk 5]
```diff
@@ -1,24 +1,45 @@
...
   options: CursorOptions;
   aria: Aria;
   ariaLabel: string;
   ariaPostLabel: string;
-  cursor: Cursor;
+  readonly cursor: Cursor;
```
Comment (kschaefe) [inline src/controller.ts:25]: Remove in favor of constructor definition.

**Review by kschaefe — COMMENTED** [review]
Quick pass.  Found a bunch of TypeScript nits.  Nothing that would block merging, but some clean up we can add for the future.

File: src/controller.ts [hunk 6]
```diff
@@ -1,24 +1,45 @@
...
+    [K in keyof HTMLElementEventMap]: (event: HTMLElementEventMap[K]) => any;
+  }> = {};
+
+  textareaSpan: HTMLElement | undefined;
+  mathspeakSpan: HTMLElement | undefined;
+
+  constructor(
+    root: ControllerRoot,
+    container: HTMLElement,
+    options: CursorOptions
```
[the remark this answers is not in the document]
Comment (jwmerrill) [reply src/controller.ts]: I attempted to make these `private readonly`, but it turns out they're all read from outside the class definition, so I just made them `readonly`.

File: src/controller.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (jwmerrill) [reply src/controller.ts:22]: I don't understand this suggestion.

File: src/cursor.ts [hunk 7]
```diff
@@ -12,7 +12,7 @@ JS environment could actually contain many instances. */
 //A fake cursor in the fake textbox that the math is rendered in.
 class Anticursor extends Point {
   ancestors: Record<string | number, Anticursor | MQNode | undefined> = {};
-  constructor(parent: MQNode, leftward?: NodeRef, rightward?: NodeRef) {
+  constructor(parent: MQNode, leftward: NodeRef, rightward: NodeRef) {
```
[the remark this answers is not in the document]
Comment (jwmerrill) [reply src/cursor.ts]: Addressed in 5623ddee71633c0331510c41f9cced49a2dfe07f

File: src/cursor.ts (hunk 2 above)
Comment (jwmerrill) [reply src/cursor.ts]: Addressed in 5623ddee71633c0331510c41f9cced49a2dfe07f

File: src/controller.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (jwmerrill) [reply src/controller.ts]: Addressed in 5623ddee71633c0331510c41f9cced49a2dfe07f

File: src/controller.ts (hunk 3 above)
Comment (jwmerrill) [reply src/controller.ts:30]: I'm not sure how to express this using `Record`.

File: src/controller.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (jwmerrill) [reply src/controller.ts:22]: The constructor doesn't take `cursor` as an argument. It creates a new cursor.

File: src/controller.ts (hunk 3 above)
Comment (jwmerrill) [reply src/controller.ts:30]: That syntax doesn't appear to work, and neither does
```ts
Record<K in keyof HTMLElementEventMap, (event: HTMLElementEventMap[K]) => any>
```
or
```ts
Record<K extends keyof HTMLElementEventMap, (event: HTMLElementEventMap[K]) => any>
```

TS gives me `Cannot find name 'K'`.

Comment (kschaefe) [reply src/controller.ts:30]: Right.  Never mind on this one.

File: src/controller.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (kschaefe) [reply src/controller.ts:22]: Ah, you're right.  It takes CursorOptions to make the Cursor.

**Comment by FlamedDogo99** [comment]
Do we have a timeline on when this will be reviewed?

**Review by jaltekruse — APPROVED** [review]
+1

I'm going to go ahead and merge this. Desmos has been shipping it for 2 years at this point, and the Khan Academy team has their branch based on this work. I can't make too many hard promises, but I'm hoping to be more active in the next few months and may be able to work on getting more of the work that is out in the forks merged into mainline as well, but it seems like merging this is a good first step.

**Comment by jaltekruse** [comment]
Should have made CI re-run first... I'll work on the build failure tomorrow.
