### PR TITLE
Handling of empty TextBlocks

### LINKED ISSUE #126: On dev, leaving an empty \text{} rendered from LaTeX will error
In `\text{NaN}` test case (on `test/visual.html`), backspace or delete forward until empty, then move out with arrow keys or backspace and delete again.

(Same root cause as #121.)

### LINKED ISSUE #313: [dev] Pasting `\text{}` causes an error
Pasting `\text{foo}` works fine, but `\text{}`causes an error in `fuseChildren`: "Cannot read property 'data' of null".

On a related note, typing `\text` and then anything will also cause a JS error (sometimes in the same place as above, sometimes elsewhere).

Found this while fuzz testing (aka key mashing) - some combination of valid key presses seems to insert `\text{}`, but I couldn't track down which one.

### LINKED ISSUE #429: [dev] TextBlock's latex changes to \text{undefined} after moving cursor to the left
Hi, I noticed this behaviour on dev. I added [a simple failing test on my fork](https://github.com/Learnosity/mathquill/commit/63c50e8df50269752c2523b6a587db8ad17f2c79) to illustrate.

To test manually:
- Input `\text{x}` (by any method)
- Using arrow key, move cursor back to the left of the `x`
- Latex output is now `\text{undefined}`

### PR DESCRIPTION
**Pull request by laughinghan**
Work in progress for #474.

- Fixes #126
- Fixes #313
- Incorporates PR #430 which fixes #429

### CODE REVIEW

**Comment by FWennerdahl** [comment]
I'll take a look at resolving the merge conflicts in this asap.

**Comment by laughinghan** [comment]
You rock

**Comment by laughinghan** [comment]
There's a good chance the merge conflict is just with #528, which like #430 (which is the first few commits here) fixes #429. (For why #430 wasn't merged, see here: https://github.com/mathquill/mathquill/pull/430#issuecomment-188494935 )

**Comment by FWennerdahl** [comment]
I tested the master branch to verify that this PR is still relevant. When moving out of an empty text block I got

    Uncaught TypeError: Cannot read property 'nodeType' of null
which this PR adresses along with the other changes detailed in #474.

Not sure what to do about the missing CLA signing, perhaps @eoghanmcilwaine would be willing to pop by and sign it :)

In the worst case I'd have to migrate my commits to a new branch.

**Comment by eoghanmcilwaine** [comment]
No worries @FWennerdahl - just signed the CLA. Sorry for the delay, I've just returned to reality after a ridiculously long air journey :sweat_smile:

**Comment by FWennerdahl** [comment]
Thanks @eoghanmcilwaine! However, it seems that something happened which caused all agreements to become unsigned again (was the CLA updated? I couldn't see anything new in it).

**Comment by eoghanmcilwaine** [comment]
Odd, doesn't look like it's changed. Just signed again anyway.

File: src/services/latex.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
 var latexMathParser = (function() {
   function commandToBlock(cmd) {
     var block = MathBlock();
-    cmd.adopt(block, 0, 0);
+    if (cmd) cmd.adopt(block, 0, 0);
```
Comment (laughinghan) [inline src/services/latex.js]: minor thing: don't need this, parsers can return empty `Fragment()`s

(I'll fix)

File: test/unit/backspace.test.js [hunk 2]
```diff
@@ -206,6 +206,23 @@ suite('backspace', function() {
...
+    mq.keystroke('Backspace');
+    assert.equal(cursor.parent, textBlock, 'cursor is still in text block');
+    assert.equal(cursor[R], 0, 'cursor is at the right end of the text block');
+    assert.equal(cursor[L], 0, 'cursor is at the left end of the text block');
+    assert.equal(mq.latex(), '', 'the x has been deleted');
+
+    mq.keystroke('Backspace');
+    assert.equal(cursor.parent, rootBlock, 'cursor is in root block');
+    assert.equal(cursor[L], textBlock, 'cursor is to the right of the text block');
+    assert.equal(mq.latex(), '', 'text block still empty');
```
Comment (laughinghan) [inline test/unit/backspace.test.js]: wouldn't you want this backspace to delete the textblock rather than just inserting the cursor to the right? It used to be that blurring an empty textblock would delete it, that's why `deleteOutOf` just inserts the cursor right outside

**Comment by laughinghan** [comment]
@eoghanmcilwaine @FWennerdahl thanks for your patience you guys! I don't know what we've done to deserve contributors like you

Was kinda cowboy about merging this with my fixes since it's actually a really easy case to stumble onto thanks to the quirky `\somethingThatsNotLatex` turning into `\text{somethingThatsNotLatex}` feature

**Comment by laughinghan** [comment]
Note: merged into `master` with additional commits (b435621)

(See `git log --oneline b435621^..b435621^2`)

**Comment by eoghanmcilwaine** [comment]
Nice! Thanks @laughinghan and @FWennerdahl .
